# Generated by Django 4.2 on 2025-06-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_code', models.CharField(max_length=80, unique=True)),
                ('in_game_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSelectedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.chatoptionnode')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.playersession')),
            ],
        ),
    ]
