# Generated by Django 4.2 on 2025-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_playersession_playerselectednode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playerselectednode',
            constraint=models.UniqueConstraint(fields=('player', 'node'), name='unique_player_selected_node'),
        ),
    ]
