# Generated by Django 4.2 on 2025-06-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_playerselectednode_unique_player_selected_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time_was_written',
            new_name='custom_writing_delay',
        ),
    ]
