# Generated by Django 4.2 on 2025-06-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_rename_time_was_written_message_custom_writing_delay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='custom_writing_delay',
            new_name='typing_delay_override_ms',
        ),
    ]
