# Generated by Django 4.2 on 2025-06-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_rename_custom_writing_delay_message_typing_delay_override_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/chats/'),
        ),
    ]
