# Generated by Django 4.2 on 2025-07-15 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_remove_chat_is_group_chat_is_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='root_node',
        ),
        migrations.CreateModel(
            name='EntryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.chatoptionnode')),
            ],
        ),
    ]
