# Generated by Django 4.2 on 2025-07-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_alter_entrynode_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynode',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='MainApp.chatoptionnode'),
        ),
    ]
