# Generated by Django 4.2 on 2025-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_chatoptionnode_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatoptionnode',
            old_name='short_description',
            new_name='user_choice_text',
        ),
        migrations.AddField(
            model_name='chatoptionnode',
            name='type',
            field=models.CharField(blank=True, default='choice', max_length=50),
        ),
    ]
