# Generated by Django 4.2 on 2025-07-18 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_rename_short_description_chatoptionnode_user_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatoptionnode',
            name='user_choice_lasts_for',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='chatoptionnode',
            name='user_choice_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 0, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
