# Generated by Django 4.2 on 2025-07-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_chatoptionnode_user_choice_lasts_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='delay_ms',
            field=models.BigIntegerField(default=0),
        ),
    ]
