# Generated by Django 4.2 on 2025-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_remove_message_timestamp_message_delay_ms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatoptionnode',
            old_name='user_choice_lasts_for',
            new_name='choice_lasts_for_ms',
        ),
        migrations.RenameField(
            model_name='chatoptionnode',
            old_name='user_choice_text',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='chatoptionnode',
            name='user_choice_start_time',
        ),
        migrations.AddField(
            model_name='chatoptionnode',
            name='choice_delay_ms',
            field=models.BigIntegerField(default=0),
        ),
    ]
