# Generated by Django 4.2 on 2025-07-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_rename_user_choice_lasts_for_chatoptionnode_choice_lasts_for_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatoptionnode',
            name='choice_lasts_for_ms',
            field=models.IntegerField(default=10000),
        ),
    ]
