# Generated by Django 4.2 on 2025-07-31 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_alter_chatoptionnode_choice_lasts_for_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerselectednode',
            name='time_selected',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 2, 41, 43, 678134, tzinfo=datetime.timezone.utc)),
        ),
    ]
