# Generated by Django 4.2 on 2025-08-06 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_playerselectednode_time_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatoptionnode',
            name='default_selected_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerselectednode',
            name='time_selected',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 11, 51, 13, 418643, tzinfo=datetime.timezone.utc)),
        ),
    ]
