# Generated by Django 4.2 on 2025-08-08 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_chatoptionnode_default_selected_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselectednode',
            name='time_selected',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 21, 49, 59, 54500, tzinfo=datetime.timezone.utc)),
        ),
    ]
