# Generated by Django 5.2.5 on 2025-08-13 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_alter_playerselectednode_time_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='volume_music',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersession',
            name='volume_sfx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerselectednode',
            name='time_selected',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 20, 4, 54, 195139, tzinfo=datetime.timezone.utc)),
        ),
    ]
